server:
  port: 2020
spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
wx:
  miniapp:
    configs:
      - appid: 
        secret: 
        token:
        aesKey:
        msgDataFormat: JSON
